version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 10380:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
  php:
    build:
      context: ./docker/php
      args:
        DOCKER_UID: ${DOCKER_UID:-1000}
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker_db_user
      MYSQL_PASSWORD: docker_db_user_pass
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 10381:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
